import starlight from '@astrojs/starlight';
import tailwindcss from '@tailwindcss/vite';
import { defineConfig } from 'astro/config';

export default defineConfig({
  // The apex, per ADR 0005. Serving from the domain root is what keeps the
  // Guide's root-absolute `/guide/…` links working: Astro does not inject a
  // `base` into links written by hand in Markdown.
  site: 'https://argusappsec.com',

  integrations: [
    starlight({
      title: 'Argus',
      // The Mirror is autogenerated wholesale, so ordering and membership stay
      // with the Guide: they come from `sidebar.order` in its own frontmatter,
      // and a page added or removed upstream needs no edit here. Only the group
      // labels belong to this repository, and they are applied in the route
      // middleware rather than declared here — ADR 0006 records why.
      sidebar: [{ autogenerate: { directory: 'guide' } }],
      routeMiddleware: './src/route-middleware.ts',
      customCss: ['./src/styles/global.css'],
    }),
  ],
  vite: { plugins: [tailwindcss()] },
});
