import starlight from '@astrojs/starlight';
import tailwindcss from '@tailwindcss/vite';
import { defineConfig } from 'astro/config';

import { linkGuard } from './src/links/guard';
import { contrastGuard } from './src/tokens/guard';

export default defineConfig({
  // The apex, per ADR 0005. Serving from the domain root is what keeps the
  // Guide's root-absolute `/guide/…` links working: Astro does not inject a
  // `base` into links written by hand in Markdown.
  site: 'https://argusappsec.com',

  integrations: [
    // ADR 0004's contrast table is what justifies the whole Token layer, so
    // the build re-measures it before rendering anything. See src/tokens/.
    contrastGuard(),

    // The other half of `argus` ADR 0022's link rule, which that ADR states and
    // leaves unenforced. It reads the rendered site, so it runs at the end of
    // the build rather than the start; ADR 0010 records the trade. See
    // src/links/.
    linkGuard(),

    starlight({
      title: 'Argus',

      // Copied once from `argusappsec/argus` under `brand/`, never synced: ADR
      // 0004 records that the artwork changes effectively never.
      //
      // The mark, not a banner. The two banner variants set their tagline at
      // 15 units in a 200-unit viewBox, which is legible across a 500px hero
      // and about three pixels tall in a nav bar — no height this bar can
      // afford fixes that. The mark carries no small type and, as the brand's
      // own README says, is what to use below 24px. So the wordmark is set as
      // text instead: Starlight paints the title in `--sl-color-text-accent`,
      // which is `primary`, so the header renders a pair the build asserts.
      logo: { src: './src/assets/brand/argus.svg' },

      // A favicon has to be served, not imported, so the mark exists twice —
      // once for Astro's image pipeline, once at a URL. Both are the same
      // upstream file.
      favicon: '/argus.svg',

      // The Mirror is autogenerated wholesale, so ordering and membership stay
      // with the Guide: they come from `sidebar.order` in its own frontmatter,
      // and a page added or removed upstream needs no edit here. Only the group
      // labels belong to this repository, and they are applied in the route
      // middleware rather than declared here — ADR 0006 records why.
      sidebar: [{ autogenerate: { directory: 'guide' } }],
      routeMiddleware: './src/route-middleware.ts',
      customCss: ['./src/styles/global.css'],
    }),
  ],
  vite: { plugins: [tailwindcss()] },
});
