import { defineRouteMiddleware } from '@astrojs/starlight/route-data';
import type { StarlightRouteData } from '@astrojs/starlight/route-data';

/**
 * Human-readable labels for the Mirror's sidebar groups. The key is the label
 * Starlight generated, which for an autogenerated group is the directory name
 * on disk, verbatim — so `channels/` and `deployment/` arrive lowercase.
 *
 * Nothing in the Guide can fix that: there is no frontmatter field and no
 * per-directory config file, so the label has to come from this repository.
 * See ADR 0006 for why it is applied here rather than declared in
 * `astro.config.mjs`.
 *
 * A directory that arrives without an entry here renders lowercase — visible,
 * and not broken.
 */
const GROUP_LABELS: Record<string, string> = {
  channels: 'Channels',
  deployment: 'Deployment',
};

function relabelGroups(entries: StarlightRouteData['sidebar']): void {
  for (const entry of entries) {
    if (entry.type !== 'group') continue;
    entry.label = GROUP_LABELS[entry.label] ?? entry.label;
    relabelGroups(entry.entries);
  }
}

export const onRequest = defineRouteMiddleware((context) => {
  relabelGroups(context.locals.starlightRoute.sidebar);
});
